export enum FormPayment {
  DEBIT_CARD= 1,
  CASH_ON_STORE= 2,
  DEPOSIT_AND_BANK_TRANSFER= 3,
  MERCADOPAGO_MONEY= 4,
  PAYPAL_MONEY= 5,
  CASH= 6,
  BANK_TERMINAL= 7,
  CHECK= 8,
  OXXO_PAY= 9,
  CREDIT_CARD= 10,
}
